# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/dolby/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/dolby

PRODUCT_COPY_FILES += \
    vendor/oneplus/dolby/proprietary/etc/permissions/com.oneplus.software.oos.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.oneplus.software.oos.xml \
    vendor/oneplus/dolby/proprietary/etc/permissions/oneplus.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/oneplus.xml \
    vendor/oneplus/dolby/proprietary/etc/permissions/privapp-com.dolby.daxappui.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-com.dolby.daxappui.xml \
    vendor/oneplus/dolby/proprietary/etc/permissions/privapp-com.dolby.daxservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-com.dolby.daxservice.xml \
    vendor/oneplus/dolby/proprietary/etc/permissions/privapp-com.oneplus.sound.tuner.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-com.oneplus.sound.tuner.xml \
    vendor/oneplus/dolby/proprietary/etc/sysconfig/config-com.dolby.daxappui.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.dolby.daxappui.xml \
    vendor/oneplus/dolby/proprietary/etc/sysconfig/config-com.dolby.daxservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.dolby.daxservice.xml \
    vendor/oneplus/dolby/proprietary/etc/sysconfig/config-com.oneplus.config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.oneplus.config.xml \
    vendor/oneplus/dolby/proprietary/etc/sysconfig/config-com.oneplus.sound.tuner.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.oneplus.sound.tuner.xml \
    vendor/oneplus/dolby/proprietary/etc/sysconfig/hiddenapi-com.dolby.daxservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-com.dolby.daxservice.xml \
    vendor/oneplus/dolby/proprietary/etc/sysconfig/hiddenapi-com.oneplus.sound.tuner.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-com.oneplus.sound.tuner.xml \
    vendor/oneplus/dolby/proprietary/lib64/vendor.dolby.hardware.dms@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.dolby.hardware.dms@2.0.so \
    vendor/oneplus/dolby/proprietary/vendor/bin/hw/vendor.dolby.hardware.dms@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.dolby.hardware.dms@2.0-service \
    vendor/oneplus/dolby/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.bass_96:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.bass_96 \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.bass_96_headphone_only:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.bass_96_headphone_only \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.bass_144:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.bass_144 \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.bass_144_headphone_only:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.bass_144_headphone_only \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.bass_192:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.bass_192 \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.bass_192_headphone_only:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.bass_192_headphone_only \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.oneplus:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.oneplus \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.oneplus_zw:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.oneplus_zw \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.orig_bug:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.orig_bug \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.orig_fix:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.orig_fix \
    vendor/oneplus/dolby/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)//etc/dolby/dax-default.xml \
    vendor/oneplus/dolby/proprietary/vendor/lib/libdapparamstorage.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdapparamstorage.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/libdeccfg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdeccfg.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/libqtigef.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqtigef.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/libstagefright_soft_ac4dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_ac4dec.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/libstagefright_soft_ddpdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_ddpdec.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/libstagefrightdolby.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrightdolby.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/vendor.dolby.hardware.dms@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.dolby.hardware.dms@2.0.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/soundfx/libeffectproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libeffectproxy.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/soundfx/libswdap.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libswdap.so \
    vendor/oneplus/dolby/proprietary/vendor/lib/soundfx/libswvqe.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libswvqe.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/libdapparamstorage.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdapparamstorage.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/libdeccfg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdeccfg.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/libdlbdsservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdlbdsservice.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/libqtigef.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqtigef.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/libstagefright_soft_ac4dec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefright_soft_ac4dec.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/libstagefright_soft_ddpdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefright_soft_ddpdec.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/libstagefrightdolby.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefrightdolby.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/vendor.dolby.hardware.dms@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.dolby.hardware.dms@2.0-impl.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/vendor.dolby.hardware.dms@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.dolby.hardware.dms@2.0.so
    vendor/oneplus/dolby/proprietary/vendor/lib64/soundfx/libeffectproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libeffectproxy.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/soundfx/libswdap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libswdap.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/soundfx/libhwdap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libhwdap.so \
    vendor/oneplus/dolby/proprietary/vendor/lib64/soundfx/libswvqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libswvqe.so 


PRODUCT_PACKAGES += \
    OPSoundTuner \
    oneplus \
    daxService \
    black_sound_tuner \
    white_sound_tuner



    // vendor/oneplus/dolby/proprietary/lib64/vendor.dolby.hardware.dms@2.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.dolby.hardware.dms@2.0.so \
    // vendor/oneplus/dolby/proprietary/odm/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_ODM)/etc/dolby/dax-default.xml \
    // vendor/oneplus/dolby/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    // vendor/oneplus/dolby/proprietary/system_ext/etc/permissions/com.dolby.daxservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.dolby.daxservice.xml \
    // vendor/oneplus/dolby/proprietary/system_ext/etc/permissions/com.oneplus.software.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.oneplus.software.xml \
    // vendor/oneplus/dolby/proprietary/vendor/bin/hw/vendor.dolby.hardware.dms@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.dolby.hardware.dms@2.0-service \
    // vendor/oneplus/dolby/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    // vendor/oneplus/dolby/proprietary/vendor/lib/libdapparamstorage.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdapparamstorage.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/libdeccfg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdeccfg.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/libqtigef.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqtigef.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/libstagefright_soft_ac4dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_ac4dec.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/libstagefright_soft_ddpdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_ddpdec.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/libstagefrightdolby.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrightdolby.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/soundfx/libeffectproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libeffectproxy.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/soundfx/libswdap.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libswdap.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/soundfx/libswgamedap.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libswgamedap.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib/vendor.dolby.hardware.dms@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.dolby.hardware.dms@2.0.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/libdapparamstorage.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdapparamstorage.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/libdeccfg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdeccfg.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/libdlbdsservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdlbdsservice.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/libqtigef.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqtigef.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/libstagefright_soft_ac4dec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefright_soft_ac4dec.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/libstagefright_soft_ddpdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefright_soft_ddpdec.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/libstagefrightdolby.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefrightdolby.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/soundfx/libeffectproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libeffectproxy.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/soundfx/libswdap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libswdap.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/soundfx/libswgamedap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/soundfx/libswgamedap.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/vendor.dolby.hardware.dms@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.dolby.hardware.dms@2.0-impl.so \
    // vendor/oneplus/dolby/proprietary/vendor/lib64/vendor.dolby.hardware.dms@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.dolby.hardware.dms@2.0.so
